# Generated by Django 3.0.9 on 2020-08-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birthdate',
            field=models.DateField(verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(verbose_name='birthdate'),
        ),
    ]
