# Generated by Django 3.0.9 on 2020-08-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='shift',
            field=models.CharField(choices=[('M', 'morning'), ('A', 'afternoon'), ('E', 'evening'), ('N', 'night')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('M', 'monday'), ('T', 'tuesday'), ('W', 'wednesday'), ('TH', 'thursday'), ('F', 'friday'), ('S', 'saturday'), ('SU', 'sunday')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='users.Client', verbose_name='Client'),
        ),
    ]
