# Generated by Django 3.0.9 on 2020-08-25 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200825_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='user_bbs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Babysitter'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
