# Generated by Django 3.0.9 on 2020-08-27 04:23

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200827_0353'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='availability',
            name='bbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', related_query_name='availibility', to='users.Babysitter', verbose_name='Availibility'),
        ),
    ]
