# Generated by Django 3.0.9 on 2020-08-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200827_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'monday'), ('TUESDAY', 'tuesday'), ('WEDNESDAY', 'wednesday'), ('THURSDAY', 'thursday'), ('FRIDAY', 'friday'), ('SATURDAY', 'saturday'), ('SUNDAY', 'sunday')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'morning'), ('AFTERNOON', 'afternoon'), ('EVENING', 'evening'), ('NIGHT', 'night')], default='M', max_length=10),
        ),
    ]
