# Generated by Django 3.0.9 on 2020-08-27 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200827_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='shift',
            field=models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening'), ('night', 'night')], default='morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userclient', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unspecified', 'unspecified')], default='unspecified', max_length=11),
        ),
    ]
