# Generated by Django 3.0.9 on 2020-08-27 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20200827_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('date', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('count_children', models.PositiveSmallIntegerField()),
                ('special_cares', models.CharField(blank=True, help_text='Write the special cares to consider for each child', max_length=255, null=True, verbose_name='Special Cares')),
                ('is_active', models.BooleanField(default=True, verbose_name='Service Active')),
                ('user_bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbsservice', to='users.Babysitter', verbose_name='Babysitter')),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userservice', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
