# Generated by Django 3.0.9 on 2020-08-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user_bbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbs_service', to='users.Babysitter', verbose_name='Babysitter'),
        ),
        migrations.AddField(
            model_name='service',
            name='user_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_service', to='users.Client', verbose_name='Customer'),
        ),
    ]
