# Generated by Django 3.0.9 on 2020-09-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200907_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
