# Generated by Django 3.0.9 on 2020-08-27 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200827_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime service ends'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime service starts'),
        ),
        migrations.AddField(
            model_name='service',
            name='shift',
            field=models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening'), ('night', 'night')], default='morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='count_children',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10, message='The maximum number of children per babysitter must be 10')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
