# Generated by Django 5.1.4 on 2025-12-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_auto_20200912_1923"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="on_my_way",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Babysitter on the way"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
