# Generated by Django 3.0.9 on 2020-08-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200827_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total service cost'),
        ),
    ]
