# Generated by Django 5.1.4 on 2025-12-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_add_on_my_way_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="scheduled_start",
            field=models.DateTimeField(
                blank=True,
                help_text="The scheduled start time with timezone",
                null=True,
                verbose_name="Scheduled service start time",
            ),
        ),
    ]
