# Generated by Django 5.1.4 on 2025-12-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_add_scheduled_start_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="arrival",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Babysitter arrived"
            ),
        ),
    ]
